version: '3.8'

services:
  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_app
    container_name: user_app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    depends_on:
      - db_user
    command: python main.py

  db_user:
    image: postgres:15.4
    container_name: db_user
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - user-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  user-data:
