# Generated by Django 4.2.2 on 2023-07-03 01:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CrateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=120, unique=True)),
                ("password", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("last_access", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
